name: Acquire Activation File
on:
  workflow_dispatch:  # GitHub Actions 탭에서 수동 실행
 
jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        uses: game-ci/unity-activate@v2
        id: activation
 
      - name: Upload .alf artifact
        uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: ${{ steps.activation.outputs.filePath }}
